indent_style = "Block"
tab_spaces = 2
reorder_imports = true
trailing_comma = "Vertical"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_impl_items = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = true
unstable_features = true
use_try_shorthand = true
