// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

class NativeImpl implements Native {
  final NativePlatform _platform;
  factory NativeImpl(ExternalLibrary dylib) =>
      NativeImpl.raw(NativePlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory NativeImpl.wasm(FutureOr<WasmModule> module) =>
      NativeImpl(module as ExternalLibrary);
  NativeImpl.raw(this._platform);
  Future<SerialResponse> bleGetNdid({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__get_ndid(port_),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleGetNdidConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleGetNdidConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__get_ndid",
        argNames: [],
      );

  Future<SerialResponse> bleAtNdrpt(
      {required String id,
      required String data,
      required int retry,
      dynamic hint}) {
    var arg0 = _platform.api2wire_String(id);
    var arg1 = _platform.api2wire_String(data);
    var arg2 = api2wire_u8(retry);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_ble__at_ndrpt(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleAtNdrptConstMeta,
      argValues: [id, data, retry],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleAtNdrptConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__at_ndrpt",
        argNames: ["id", "data", "retry"],
      );

  Future<SerialResponse> bleAtNdrptTest({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__at_ndrpt_test(port_),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleAtNdrptTestConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleAtNdrptTestConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__at_ndrpt_test",
        argNames: [],
      );

  Future<SerialResponse> bleSetNdid({required String id, dynamic hint}) {
    var arg0 = _platform.api2wire_String(id);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__set_ndid(port_, arg0),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleSetNdidConstMeta,
      argValues: [id],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleSetNdidConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__set_ndid",
        argNames: ["id"],
      );

  Future<SerialResponse> bleSetMode({required int mode, dynamic hint}) {
    var arg0 = api2wire_u8(mode);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__set_mode(port_, arg0),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleSetModeConstMeta,
      argValues: [mode],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleSetModeConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__set_mode",
        argNames: ["mode"],
      );

  Future<SerialResponse> bleNdreset({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__ndreset(port_),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleNdresetConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleNdresetConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__ndreset",
        argNames: [],
      );

  Future<SerialResponse> bleRestore({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__restore(port_),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleRestoreConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleRestoreConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__restore",
        argNames: [],
      );

  Future<SerialResponse> bleReboot({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_ble__reboot(port_),
      parseSuccessData: _wire2api_serial_response,
      constMeta: kBleRebootConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBleRebootConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "ble__reboot",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  int _wire2api_i32(dynamic raw) {
    return raw as int;
  }

  Uint8List? _wire2api_opt_uint_8_list(dynamic raw) {
    return raw == null ? null : _wire2api_uint_8_list(raw);
  }

  ResponseState _wire2api_response_state(dynamic raw) {
    return ResponseState.values[raw];
  }

  SerialResponse _wire2api_serial_response(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SerialResponse(
      state: _wire2api_response_state(arr[0]),
      data: _wire2api_opt_uint_8_list(arr[1]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class NativePlatform extends FlutterRustBridgeBase<NativeWire> {
  NativePlatform(ffi.DynamicLibrary dylib) : super(NativeWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class NativeWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_ble__get_ndid(
    int port_,
  ) {
    return _wire_ble__get_ndid(
      port_,
    );
  }

  late final _wire_ble__get_ndidPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_ble__get_ndid');
  late final _wire_ble__get_ndid =
      _wire_ble__get_ndidPtr.asFunction<void Function(int)>();

  void wire_ble__at_ndrpt(
    int port_,
    ffi.Pointer<wire_uint_8_list> id,
    ffi.Pointer<wire_uint_8_list> data,
    int retry,
  ) {
    return _wire_ble__at_ndrpt(
      port_,
      id,
      data,
      retry,
    );
  }

  late final _wire_ble__at_ndrptPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>, ffi.Uint8)>>('wire_ble__at_ndrpt');
  late final _wire_ble__at_ndrpt = _wire_ble__at_ndrptPtr.asFunction<
      void Function(int, ffi.Pointer<wire_uint_8_list>,
          ffi.Pointer<wire_uint_8_list>, int)>();

  void wire_ble__at_ndrpt_test(
    int port_,
  ) {
    return _wire_ble__at_ndrpt_test(
      port_,
    );
  }

  late final _wire_ble__at_ndrpt_testPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_ble__at_ndrpt_test');
  late final _wire_ble__at_ndrpt_test =
      _wire_ble__at_ndrpt_testPtr.asFunction<void Function(int)>();

  void wire_ble__set_ndid(
    int port_,
    ffi.Pointer<wire_uint_8_list> id,
  ) {
    return _wire_ble__set_ndid(
      port_,
      id,
    );
  }

  late final _wire_ble__set_ndidPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_ble__set_ndid');
  late final _wire_ble__set_ndid = _wire_ble__set_ndidPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_ble__set_mode(
    int port_,
    int mode,
  ) {
    return _wire_ble__set_mode(
      port_,
      mode,
    );
  }

  late final _wire_ble__set_modePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint8)>>(
          'wire_ble__set_mode');
  late final _wire_ble__set_mode =
      _wire_ble__set_modePtr.asFunction<void Function(int, int)>();

  void wire_ble__ndreset(
    int port_,
  ) {
    return _wire_ble__ndreset(
      port_,
    );
  }

  late final _wire_ble__ndresetPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_ble__ndreset');
  late final _wire_ble__ndreset =
      _wire_ble__ndresetPtr.asFunction<void Function(int)>();

  void wire_ble__restore(
    int port_,
  ) {
    return _wire_ble__restore(
      port_,
    );
  }

  late final _wire_ble__restorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_ble__restore');
  late final _wire_ble__restore =
      _wire_ble__restorePtr.asFunction<void Function(int)>();

  void wire_ble__reboot(
    int port_,
  ) {
    return _wire_ble__reboot(
      port_,
    );
  }

  late final _wire_ble__rebootPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_ble__reboot');
  late final _wire_ble__reboot =
      _wire_ble__rebootPtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
