#![allow(
  non_camel_case_types,
  unused,
  clippy::redundant_closure,
  clippy::useless_conversion,
  clippy::unit_arg,
  clippy::double_parens,
  non_snake_case,
  clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.75.1.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::{ffi::c_void, sync::Arc};

// Section: imports

use crate::ble::{ResponseState, SerialResponse};

// Section: wire functions

fn wire_ble__get_ndid_impl(port_: MessagePort) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__get_ndid",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || move |task_callback| Ok(ble__get_ndid()),
  )
}
fn wire_ble__at_ndrpt_impl(
  port_: MessagePort,
  id: impl Wire2Api<String> + UnwindSafe,
  data: impl Wire2Api<String> + UnwindSafe,
  retry: impl Wire2Api<u8> + UnwindSafe,
) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__at_ndrpt",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || {
      let api_id = id.wire2api();
      let api_data = data.wire2api();
      let api_retry = retry.wire2api();
      move |task_callback| Ok(ble__at_ndrpt(api_id, api_data, api_retry))
    },
  )
}
fn wire_ble__at_ndrpt_test_impl(port_: MessagePort) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__at_ndrpt_test",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || move |task_callback| Ok(ble__at_ndrpt_test()),
  )
}
fn wire_ble__set_ndid_impl(port_: MessagePort, id: impl Wire2Api<String> + UnwindSafe) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__set_ndid",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || {
      let api_id = id.wire2api();
      move |task_callback| Ok(ble__set_ndid(api_id))
    },
  )
}
fn wire_ble__set_mode_impl(port_: MessagePort, mode: impl Wire2Api<u8> + UnwindSafe) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__set_mode",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || {
      let api_mode = mode.wire2api();
      move |task_callback| Ok(ble__set_mode(api_mode))
    },
  )
}
fn wire_ble__ndreset_impl(port_: MessagePort) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__ndreset",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || move |task_callback| Ok(ble__ndreset()),
  )
}
fn wire_ble__restore_impl(port_: MessagePort) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__restore",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || move |task_callback| Ok(ble__restore()),
  )
}
fn wire_ble__reboot_impl(port_: MessagePort) {
  FLUTTER_RUST_BRIDGE_HANDLER.wrap(
    WrapInfo {
      debug_name: "ble__reboot",
      port: Some(port_),
      mode: FfiCallMode::Normal,
    },
    move || move |task_callback| Ok(ble__reboot()),
  )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
  fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
  *mut S: Wire2Api<T>,
{
  fn wire2api(self) -> Option<T> {
    (!self.is_null()).then(|| self.wire2api())
  }
}

impl Wire2Api<u8> for u8 {
  fn wire2api(self) -> u8 {
    self
  }
}

// Section: impl IntoDart

impl support::IntoDart for ResponseState {
  fn into_dart(self) -> support::DartAbi {
    match self {
      Self::Ok => 0,
      Self::FailedOpenDevice => 1,
      Self::Timeout => 2,
      Self::Unknown => 3,
      Self::MaxRetry => 4,
      Self::MaxSendRetry => 5,
      Self::ReadResponseError => 6,
    }
    .into_dart()
  }
}
impl support::IntoDartExceptPrimitive for ResponseState {}
impl support::IntoDart for SerialResponse {
  fn into_dart(self) -> support::DartAbi {
    vec![self.state.into_dart(), self.data.into_dart()].into_dart()
  }
}
impl support::IntoDartExceptPrimitive for SerialResponse {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
